from Agents.prompts.common import (
    DAY_DISCUSS_RESPONSE_FORMAT,
    DISCUSSION_SILENCE_RULE,
    GAME_PREAMBLE,
    TONE_INSTRUCTION,
    build_system_prompt,
)
from Agents.prompts.day import (
    DAY_VOTE_SYSTEM_SUFFIX,
    HEALER_DAY_DISCUSS,
    HEALER_DAY_VOTE,
    INVESTIGATOR_DAY_DISCUSS,
    INVESTIGATOR_DAY_VOTE,
    VILLAGER_DAY_DISCUSS,
    VILLAGER_DAY_VOTE,
    WOLF_DAY_DISCUSS,
    WOLF_DAY_VOTE,
)
from Agents.prompts.dedup import BATCH_DEDUP_PROMPT, PER_EXTRACTION_DEDUP_PROMPT
from Agents.prompts.extraction import DAY_SUMMARY_PROMPT, POSTGAME_EXTRACTION_PROMPT
from Agents.prompts.memory import (
    DAY_DISCUSSION_MEMORY_CONTEXT,
    DAY_VOTE_MEMORY_CONTEXT,
    SITUATION_ROLE_LENS,
    SITUATION_SUMMARY_PROMPT,
)
from Agents.prompts.night import HEALER_NIGHT, INVESTIGATOR_NIGHT, WOLF_NIGHT_DISCUSS
from Agents.prompts.roles import (
    HEALER_CORE_STRATEGY,
    INVESTIGATOR_CORE_STRATEGY,
    ROLE_CORE_STRATEGY,
    ROLE_IDENTITY,
    VILLAGER_CORE_STRATEGY,
    WOLF_CORE_STRATEGY,
)
from Agents.prompts.standards import SITUATION_STANDARDS

__all__ = [
    "BATCH_DEDUP_PROMPT",
    "DAY_DISCUSS_RESPONSE_FORMAT",
    "DAY_DISCUSSION_MEMORY_CONTEXT",
    "DAY_SUMMARY_PROMPT",
    "DAY_VOTE_MEMORY_CONTEXT",
    "DAY_VOTE_SYSTEM_SUFFIX",
    "DISCUSSION_SILENCE_RULE",
    "GAME_PREAMBLE",
    "HEALER_CORE_STRATEGY",
    "HEALER_DAY_DISCUSS",
    "HEALER_DAY_VOTE",
    "HEALER_NIGHT",
    "INVESTIGATOR_CORE_STRATEGY",
    "INVESTIGATOR_DAY_DISCUSS",
    "INVESTIGATOR_DAY_VOTE",
    "INVESTIGATOR_NIGHT",
    "PER_EXTRACTION_DEDUP_PROMPT",
    "POSTGAME_EXTRACTION_PROMPT",
    "ROLE_CORE_STRATEGY",
    "ROLE_IDENTITY",
    "SITUATION_ROLE_LENS",
    "SITUATION_STANDARDS",
    "SITUATION_SUMMARY_PROMPT",
    "TONE_INSTRUCTION",
    "VILLAGER_CORE_STRATEGY",
    "VILLAGER_DAY_DISCUSS",
    "VILLAGER_DAY_VOTE",
    "WOLF_CORE_STRATEGY",
    "WOLF_DAY_DISCUSS",
    "WOLF_DAY_VOTE",
    "WOLF_NIGHT_DISCUSS",
    "build_system_prompt",
]
