"""Pydantic schemas, grouped by concern (re-exported flat for convenience).

output.py + the extraction/rerank models in memory.py are MODEL-VISIBLE structured-output contracts
(frozen — their schema is sent to the model); game_events / scheduler / metrics / evaluation and the
store/retrieval models in memory.py are internal records (state / tracing / storage), never sent to a
model.
"""

from Agents.schemas.roles import ActionPhase
from Agents.schemas.evaluation import (
    DaySummaryCase,
    DedupCandidate,
    DedupCase,
    EvalCase,
    EvalPrivateContext,
    EvalProvenance,
    ExtractionCase,
    NightAction,
)
from Agents.schemas.game_events import (
    AddressedTarget,
    DayChannel,
    DaySummary,
    DayVote,
    DeathRecord,
    DiscussionPassReason,
    FiringReason,
    InvestigatorResult,
    NightActionRecord,
    WolfChannel,
)
from Agents.schemas.human_player import (
    HumanTurnRequest,
    HumanTurnResponse,
)
from Agents.schemas.memory import (
    CandidateRelevance,
    GameStrategyOutput,
    Observation,
    RerankResult,
    RetrievedObservation,
    RetrievedStrategyPoint,
    StoredObservation,
    StoredStrategy,
    StoredStrategyPoint,
    StrategyPoint,
)
from Agents.schemas.metrics import (
    ComputedGameMetrics,
    DayResolutionMetric,
    GameOutcome,
    GraphContext,
    Metrics,
    NightResolutionMetric,
)
from Agents.schemas.output import (
    AddressingExtraction,
    DayDiscussOutput,
    DaySummaryOutput,
    DaySummaryOutputV2,
    DaySummaryOutputV3,
    DaySummaryOutputV4,
    DayVoteOutput,
    HealerOutput,
    InvestigatorOutput,
    NoveltyJudgment,
    SerialKillerOutput,
    SituationSummary,
    OpeningVerdict,
    OpeningVerdicts,
    RoundEchoVerdict,
    RoundEchoVerdicts,
    VigilanteOutput,
    WolfNightDiscussOutput,
    WolfNightVoteOutput,
)
from Agents.schemas.scheduler import (
    Balance,
    Decision,
    ReactiveItem,
)
from Agents.schemas.turn import (
    ResolvedDayDiscussion,
    ResolvedDayVote,
    ResolvedHealerTarget,
    ResolvedInvestigatorTarget,
    ResolvedSerialKillerTarget,
    ResolvedTurn,
    ResolvedVigilanteTarget,
    ResolvedWolfDiscussion,
    ResolvedWolfVote,
    TurnEffects,
    TurnKind,
)


__all__ = [
    "ActionPhase",
    "AddressedTarget",
    "AddressingExtraction",
    "Balance",
    "CandidateRelevance",
    "ComputedGameMetrics",
    "DedupCandidate",
    "DedupCase",
    "DayChannel",
    "DayDiscussOutput",
    "DayResolutionMetric",
    "DaySummary",
    "DaySummaryCase",
    "DaySummaryOutput",
    "DaySummaryOutputV2",
    "DaySummaryOutputV3",
    "DaySummaryOutputV4",
    "DayVote",
    "DayVoteOutput",
    "DeathRecord",
    "Decision",
    "DiscussionPassReason",
    "EvalCase",
    "EvalPrivateContext",
    "EvalProvenance",
    "NightAction",
    "ExtractionCase",
    "FiringReason",
    "GameOutcome",
    "GameStrategyOutput",
    "GraphContext",
    "HealerOutput",
    "HumanTurnRequest",
    "HumanTurnResponse",
    "InvestigatorOutput",
    "InvestigatorResult",
    "NightActionRecord",
    "Metrics",
    "NightResolutionMetric",
    "NoveltyJudgment",
    "Observation",
    "ReactiveItem",
    "ResolvedDayDiscussion",
    "ResolvedDayVote",
    "OpeningVerdict",
    "OpeningVerdicts",
    "RoundEchoVerdict",
    "RoundEchoVerdicts",
    "ResolvedHealerTarget",
    "ResolvedInvestigatorTarget",
    "ResolvedSerialKillerTarget",
    "ResolvedTurn",
    "ResolvedVigilanteTarget",
    "ResolvedWolfDiscussion",
    "ResolvedWolfVote",
    "SerialKillerOutput",
    "VigilanteOutput",
    "RerankResult",
    "RetrievedObservation",
    "RetrievedStrategyPoint",
    "SituationSummary",
    "StoredObservation",
    "StoredStrategy",
    "StoredStrategyPoint",
    "StrategyPoint",
    "TurnEffects",
    "TurnKind",
    "WolfChannel",
    "WolfNightDiscussOutput",
    "WolfNightVoteOutput",
]
