"""Memory-related prompts, split by concern: decision-time injection blocks (`context`), the live
retrieval-query prompts (`situation_summary`), and the rerank prompt (`rerank`). Re-exported flat so
`from Agents.prompts.memory import X` and `from Agents.prompts import X` both keep working unchanged.
"""

from Agents.prompts.memory.context import (
    ADOPTION_INSTRUCTION,
    DAY_DISCUSSION_MEMORY_CONTEXT,
    DAY_VOTE_MEMORY_CONTEXT,
    MEMORY_APPLICABILITY_INSTRUCTION,
    NIGHT_ACTION_MEMORY_CONTEXT,
)
from Agents.prompts.memory.rerank import RERANK_PROMPT
from Agents.prompts.memory.situation_summary import (
    HEALER_SITUATION_SUMMARY,
    INVESTIGATOR_SITUATION_SUMMARY,
    SERIAL_KILLER_SITUATION_SUMMARY,
    SITUATION_ROLE_LENS,
    SITUATION_SUMMARY_PROMPT,
    SITUATION_SUMMARY_SUFFIX,
    V6_SITUATION_SUMMARY,
    V6_SITUATION_SUMMARY_SUFFIX,
    VIGILANTE_SITUATION_SUMMARY,
    VILLAGER_SITUATION_SUMMARY,
    WOLF_SITUATION_SUMMARY,
)

__all__ = [
    "ADOPTION_INSTRUCTION",
    "DAY_DISCUSSION_MEMORY_CONTEXT",
    "DAY_VOTE_MEMORY_CONTEXT",
    "HEALER_SITUATION_SUMMARY",
    "INVESTIGATOR_SITUATION_SUMMARY",
    "MEMORY_APPLICABILITY_INSTRUCTION",
    "NIGHT_ACTION_MEMORY_CONTEXT",
    "RERANK_PROMPT",
    "SERIAL_KILLER_SITUATION_SUMMARY",
    "SITUATION_ROLE_LENS",
    "SITUATION_SUMMARY_PROMPT",
    "SITUATION_SUMMARY_SUFFIX",
    "V6_SITUATION_SUMMARY",
    "V6_SITUATION_SUMMARY_SUFFIX",
    "VIGILANTE_SITUATION_SUMMARY",
    "VILLAGER_SITUATION_SUMMARY",
    "WOLF_SITUATION_SUMMARY",
]
