// Generated by scripts/bake-sets.mjs: do not edit. The car's set as one picture per hour,
// HUD and side, at three scales (instruments/Backdrop.tsx picks one for the screen).
// 48 sheets, 8.8 MB.
import type { StaticImageData } from 'next/image';
import s_day_live_full_1 from './sets/car-day-live-full@1x.webp';
import s_day_live_side_1 from './sets/car-day-live-side@1x.webp';
import s_day_replay_full_1 from './sets/car-day-replay-full@1x.webp';
import s_day_replay_side_1 from './sets/car-day-replay-side@1x.webp';
import s_dusk_live_full_1 from './sets/car-dusk-live-full@1x.webp';
import s_dusk_live_side_1 from './sets/car-dusk-live-side@1x.webp';
import s_dusk_replay_full_1 from './sets/car-dusk-replay-full@1x.webp';
import s_dusk_replay_side_1 from './sets/car-dusk-replay-side@1x.webp';
import s_night_live_full_1 from './sets/car-night-live-full@1x.webp';
import s_night_live_side_1 from './sets/car-night-live-side@1x.webp';
import s_night_replay_full_1 from './sets/car-night-replay-full@1x.webp';
import s_night_replay_side_1 from './sets/car-night-replay-side@1x.webp';
import s_dawn_live_full_1 from './sets/car-dawn-live-full@1x.webp';
import s_dawn_live_side_1 from './sets/car-dawn-live-side@1x.webp';
import s_dawn_replay_full_1 from './sets/car-dawn-replay-full@1x.webp';
import s_dawn_replay_side_1 from './sets/car-dawn-replay-side@1x.webp';
import s_day_live_full_1_5 from './sets/car-day-live-full@1.5x.webp';
import s_day_live_side_1_5 from './sets/car-day-live-side@1.5x.webp';
import s_day_replay_full_1_5 from './sets/car-day-replay-full@1.5x.webp';
import s_day_replay_side_1_5 from './sets/car-day-replay-side@1.5x.webp';
import s_dusk_live_full_1_5 from './sets/car-dusk-live-full@1.5x.webp';
import s_dusk_live_side_1_5 from './sets/car-dusk-live-side@1.5x.webp';
import s_dusk_replay_full_1_5 from './sets/car-dusk-replay-full@1.5x.webp';
import s_dusk_replay_side_1_5 from './sets/car-dusk-replay-side@1.5x.webp';
import s_night_live_full_1_5 from './sets/car-night-live-full@1.5x.webp';
import s_night_live_side_1_5 from './sets/car-night-live-side@1.5x.webp';
import s_night_replay_full_1_5 from './sets/car-night-replay-full@1.5x.webp';
import s_night_replay_side_1_5 from './sets/car-night-replay-side@1.5x.webp';
import s_dawn_live_full_1_5 from './sets/car-dawn-live-full@1.5x.webp';
import s_dawn_live_side_1_5 from './sets/car-dawn-live-side@1.5x.webp';
import s_dawn_replay_full_1_5 from './sets/car-dawn-replay-full@1.5x.webp';
import s_dawn_replay_side_1_5 from './sets/car-dawn-replay-side@1.5x.webp';
import s_day_live_full_2 from './sets/car-day-live-full@2x.webp';
import s_day_live_side_2 from './sets/car-day-live-side@2x.webp';
import s_day_replay_full_2 from './sets/car-day-replay-full@2x.webp';
import s_day_replay_side_2 from './sets/car-day-replay-side@2x.webp';
import s_dusk_live_full_2 from './sets/car-dusk-live-full@2x.webp';
import s_dusk_live_side_2 from './sets/car-dusk-live-side@2x.webp';
import s_dusk_replay_full_2 from './sets/car-dusk-replay-full@2x.webp';
import s_dusk_replay_side_2 from './sets/car-dusk-replay-side@2x.webp';
import s_night_live_full_2 from './sets/car-night-live-full@2x.webp';
import s_night_live_side_2 from './sets/car-night-live-side@2x.webp';
import s_night_replay_full_2 from './sets/car-night-replay-full@2x.webp';
import s_night_replay_side_2 from './sets/car-night-replay-side@2x.webp';
import s_dawn_live_full_2 from './sets/car-dawn-live-full@2x.webp';
import s_dawn_live_side_2 from './sets/car-dawn-live-side@2x.webp';
import s_dawn_replay_full_2 from './sets/car-dawn-replay-full@2x.webp';
import s_dawn_replay_side_2 from './sets/car-dawn-replay-side@2x.webp';

export type SetScale = '1' | '1.5' | '2';
type Sheet = Record<SetScale, StaticImageData>;
type Sides = { full: Sheet; side: Sheet };
type Huds = { live: Sides; replay: Sides };

export const SETS: { car: Record<'day' | 'dusk' | 'night' | 'dawn', Huds> } = {
  car: {
    day: {
      live: {
        full: {
          '1': s_day_live_full_1,
          '1.5': s_day_live_full_1_5,
          '2': s_day_live_full_2,
        },
        side: {
          '1': s_day_live_side_1,
          '1.5': s_day_live_side_1_5,
          '2': s_day_live_side_2,
        },
      },
      replay: {
        full: {
          '1': s_day_replay_full_1,
          '1.5': s_day_replay_full_1_5,
          '2': s_day_replay_full_2,
        },
        side: {
          '1': s_day_replay_side_1,
          '1.5': s_day_replay_side_1_5,
          '2': s_day_replay_side_2,
        },
      },
    },
    dusk: {
      live: {
        full: {
          '1': s_dusk_live_full_1,
          '1.5': s_dusk_live_full_1_5,
          '2': s_dusk_live_full_2,
        },
        side: {
          '1': s_dusk_live_side_1,
          '1.5': s_dusk_live_side_1_5,
          '2': s_dusk_live_side_2,
        },
      },
      replay: {
        full: {
          '1': s_dusk_replay_full_1,
          '1.5': s_dusk_replay_full_1_5,
          '2': s_dusk_replay_full_2,
        },
        side: {
          '1': s_dusk_replay_side_1,
          '1.5': s_dusk_replay_side_1_5,
          '2': s_dusk_replay_side_2,
        },
      },
    },
    night: {
      live: {
        full: {
          '1': s_night_live_full_1,
          '1.5': s_night_live_full_1_5,
          '2': s_night_live_full_2,
        },
        side: {
          '1': s_night_live_side_1,
          '1.5': s_night_live_side_1_5,
          '2': s_night_live_side_2,
        },
      },
      replay: {
        full: {
          '1': s_night_replay_full_1,
          '1.5': s_night_replay_full_1_5,
          '2': s_night_replay_full_2,
        },
        side: {
          '1': s_night_replay_side_1,
          '1.5': s_night_replay_side_1_5,
          '2': s_night_replay_side_2,
        },
      },
    },
    dawn: {
      live: {
        full: {
          '1': s_dawn_live_full_1,
          '1.5': s_dawn_live_full_1_5,
          '2': s_dawn_live_full_2,
        },
        side: {
          '1': s_dawn_live_side_1,
          '1.5': s_dawn_live_side_1_5,
          '2': s_dawn_live_side_2,
        },
      },
      replay: {
        full: {
          '1': s_dawn_replay_full_1,
          '1.5': s_dawn_replay_full_1_5,
          '2': s_dawn_replay_full_2,
        },
        side: {
          '1': s_dawn_replay_side_1,
          '1.5': s_dawn_replay_side_1_5,
          '2': s_dawn_replay_side_2,
        },
      },
    },
  },
};
