// Bake the car's set (build log §8.3): photograph the bake bench for every hour, HUD and side
// at 1×, 1.5× and 2×, save WebP sheets to src/assets/sets/, and write src/assets/sets.ts so the
// Backdrop can import them. Needs a workbench serving the bench (the Playwright dev server):
//
//   WORKBENCH_URL=http://localhost:3121 node scripts/bake-sets.mjs
//
// Rerun whenever the car's paint or haze changes; the goldens then say whether the sheets did.
import { mkdir, writeFile } from 'node:fs/promises';
import { chromium } from '@playwright/test';
import sharp from 'sharp';

const base = process.env.WORKBENCH_URL ?? 'http://localhost:3121';
const PHASES = ['day', 'dusk', 'night', 'dawn'];
const HUDS = ['live', 'replay'];
const SIDES = ['full', 'side'];
const SCALES = [1, 1.5, 2];
const W = 2200,
  H = 900;
const OUT = 'src/assets/sets';

await mkdir(OUT, { recursive: true });
const browser = await chromium.launch();
const files = [];
for (const scale of SCALES) {
  const page = await browser.newPage({
    viewport: { width: W, height: H },
    deviceScaleFactor: scale,
  });
  for (const phase of PHASES)
    for (const hud of HUDS)
      for (const side of SIDES) {
        const url = `${base}/workbench/bake?phase=${phase}&hud=${hud}&side=${side === 'side' ? 1 : 0}`;
        await page.goto(url, { waitUntil: 'networkidle' });
        await page.waitForSelector('[data-bake]');
        // the dev server's badge must not end up in the sheet
        await page.addStyleTag({ content: 'nextjs-portal { display: none !important; }' });
        await page.waitForTimeout(400);
        const png = await page.screenshot({ clip: { x: 0, y: 0, width: W, height: H } });
        const name = `car-${phase}-${hud}-${side}@${scale}x.webp`;
        const { size } = await sharp(png).webp({ quality: 88 }).toFile(`${OUT}/${name}`);
        files.push({ phase, hud, side, scale: String(scale), name, size });
        console.log(`${name}  ${(size / 1024).toFixed(0)} KB`);
      }
  await page.close();
}
await browser.close();

// the manifest: static imports, so Next knows each sheet's size and hashes its URL
const ident = (f) => `s_${f.phase}_${f.hud}_${f.side}_${f.scale.replace('.', '_')}`;
const imports = files.map((f) => `import ${ident(f)} from './sets/${f.name}';`).join('\n');
const tree = PHASES.map(
  (phase) =>
    `  ${phase}: {\n` +
    HUDS.map(
      (hud) =>
        `    ${hud}: {\n` +
        SIDES.map(
          (side) =>
            `      ${side}: { ` +
            SCALES.map((scale) => {
              const f = files.find(
                (x) =>
                  x.phase === phase &&
                  x.hud === hud &&
                  x.side === side &&
                  x.scale === String(scale),
              );
              return `'${scale}': ${ident(f)}`;
            }).join(', ') +
            ` },`,
        ).join('\n') +
        `\n    },`,
    ).join('\n') +
    `\n  },`,
).join('\n');
const total = files.reduce((n, f) => n + f.size, 0);
const ts = `// Generated by scripts/bake-sets.mjs: do not edit. The car's set as one picture per hour,
// HUD and side, at three scales (instruments/Backdrop.tsx picks one for the screen).
// ${files.length} sheets, ${(total / 1024 / 1024).toFixed(1)} MB.
import type { StaticImageData } from 'next/image';
${imports}

export type SetScale = '1' | '1.5' | '2';
type Sheet = Record<SetScale, StaticImageData>;
type Sides = { full: Sheet; side: Sheet };
type Huds = { live: Sides; replay: Sides };

export const SETS: { car: Record<'day' | 'dusk' | 'night' | 'dawn', Huds> } = {
  car: {
${tree}
  },
};
`;
await writeFile('src/assets/sets.ts', ts);
console.log(
  `wrote src/assets/sets.ts: ${files.length} sheets, ${(total / 1024 / 1024).toFixed(1)} MB`,
);
