"""Prepare training data for retrieval reranker cross-encoder.

Converts golden retrieval labels into (query, document, relevance) pairs
for cross-encoder training. Reads train/val/test split from reranker_split.json
(generated by generate_split.py) to prevent data leakage.

Usage:
    poetry run python evidence/fine_tuning/cross_encoder/reranker/scripts/prep_reranker_data.py
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[5]
GOLDEN_LABELS_PATH = (
    REPO_ROOT / "evidence" / "extraction" / "situation_summary"
    / "retrieval_golden_labels.json"
)
OBS_STORE = REPO_ROOT / "Agents" / "memory_stores" / "v4_deduped_v2" / "observations.json"
SP_STORE = REPO_ROOT / "Agents" / "memory_stores" / "v4_deduped_v2" / "strategy_points.json"
OUTPUT_DIR = REPO_ROOT / "evidence" / "fine_tuning" / "cross_encoder" / "reranker" / "training_data"
SPLIT_PATH = OUTPUT_DIR / "reranker_split.json"

RELEVANCE_MAP = {0: 0.0, 1: 0.25, 2: 1.0}


def _load_memory_texts(
    sp_include_action: bool = False,
    obs_situation_only: bool = False,
) -> dict[str, str]:
    """Build the cross-encoder document text (sentence2) for every memory.

    Defaults match current production: observations are ``Situation | Approach |
    Outcome``, strategy points are situation-only.

    Two ablation knobs, each isolating one memory type:
    - ``sp_include_action``: append the strategy action to the SP situation —
      tests whether the action (which labelers saw) adds SP ranking signal.
    - ``obs_situation_only``: drop approach+outcome from observations, leaving
      ``Situation: …`` only — tests whether the pure situation-matcher design
      (situation-only for *both* types) loses observation ranking quality.

    In each case only the toggled type's text changes; the other type is
    byte-identical to the default, so it acts as a control.
    """
    key_to_text: dict[str, str] = {}

    with open(OBS_STORE) as f:
        obs_data = json.load(f)
    for items in obs_data["namespaces"].values():
        for item in items:
            val = item["value"]
            parts = [f"Situation: {val['situation']}"]
            if not obs_situation_only:
                if val.get("approach"):
                    parts.append(f"Approach: {val['approach']}")
                if val.get("outcome"):
                    parts.append(f"Outcome: {val['outcome']}")
            key_to_text[item["key"]] = " | ".join(parts)

    with open(SP_STORE) as f:
        sp_data = json.load(f)
    for items in sp_data["namespaces"].values():
        for item in items:
            val = item["value"]
            text = val["situation"]
            if sp_include_action and val.get("action"):
                text = f"{text} | Action: {val['action']}"
            key_to_text[item["key"]] = text

    return key_to_text


def _build_pairs(data: dict, key_to_text: dict[str, str]) -> list[dict]:
    pairs = []
    for case in data["labels"]:
        query = "\n".join(case["golden_situations"])
        case_idx = case["case_index"]

        for label in case.get("observation_labels", []):
            text = key_to_text.get(label["key"])
            if text is None:
                continue
            pairs.append({
                "sentence1": query,
                "sentence2": text,
                "label": RELEVANCE_MAP[label["relevance"]],
                "case_index": case_idx,
                "mem_type": "observation",
            })

        for label in case.get("strategy_labels", []):
            text = key_to_text.get(label["key"])
            if text is None:
                continue
            pairs.append({
                "sentence1": query,
                "sentence2": text,
                "label": RELEVANCE_MAP[label["relevance"]],
                "case_index": case_idx,
                "mem_type": "strategy_point",
            })
    return pairs


def _print_split_stats(pairs: list[dict], name: str) -> None:
    by_label = {0.0: 0, 0.25: 0, 1.0: 0}
    for p in pairs:
        by_label[p["label"]] += 1
    cases = sorted(set(p["case_index"] for p in pairs))
    print(f"  {name}: {len(pairs)} pairs, {len(cases)} cases")
    print(f"    irrelevant={by_label[0.0]}  partial={by_label[0.25]}  relevant={by_label[1.0]}")


def _write_jsonl(pairs: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        for p in pairs:
            f.write(json.dumps(p) + "\n")


def _load_split() -> dict[str, set[int]]:
    if not SPLIT_PATH.exists():
        raise FileNotFoundError(
            f"Split manifest not found: {SPLIT_PATH}\n"
            "Run: poetry run python evidence/fine_tuning/cross_encoder/reranker/scripts/generate_split.py"
        )
    with open(SPLIT_PATH) as f:
        manifest = json.load(f)

    labels_hash = hashlib.sha256(GOLDEN_LABELS_PATH.read_bytes()).hexdigest()
    if manifest.get("golden_labels_sha256") != labels_hash:
        print("WARNING: golden labels have changed since split was generated — "
              "consider re-running generate_split.py")

    return {
        "train": set(manifest["train"]),
        "val": set(manifest["val"]),
        "test": set(manifest["test"]),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--sp-include-action", action="store_true",
        help="Append the strategy action to the situation in sentence2 "
             "(v5 input-parity ablation). Default: situation-only (matches production).",
    )
    parser.add_argument(
        "--obs-situation-only", action="store_true",
        help="Drop approach+outcome from observations, leaving situation only "
             "(pure situation-matcher ablation). Default: Situation|Approach|Outcome "
             "(matches production).",
    )
    parser.add_argument(
        "--output-dir", type=Path, default=OUTPUT_DIR,
        help="Where to write reranker_{train,val,test}.jsonl. The case split is "
             "always read from the canonical training_data/reranker_split.json so "
             "both arms share identical splits.",
    )
    args = parser.parse_args()

    key_to_text = _load_memory_texts(
        sp_include_action=args.sp_include_action,
        obs_situation_only=args.obs_situation_only,
    )
    print(f"Loaded {len(key_to_text)} memory texts "
          f"(sp_include_action={args.sp_include_action}, "
          f"obs_situation_only={args.obs_situation_only})")

    splits = _load_split()
    print(f"Split: {len(splits['train'])} train / {len(splits['val'])} val / {len(splits['test'])} test")

    with open(GOLDEN_LABELS_PATH) as f:
        data = json.load(f)

    all_pairs = _build_pairs(data, key_to_text)

    split_pairs = {}
    for name, case_indices in splits.items():
        split_pairs[name] = [p for p in all_pairs if p["case_index"] in case_indices]

    print()
    for name in ["train", "val", "test"]:
        _print_split_stats(split_pairs[name], name)

    for name in ["train", "val", "test"]:
        _write_jsonl(split_pairs[name], args.output_dir / f"reranker_{name}.jsonl")

    print(f"\nWrote:")
    for name in ["train", "val", "test"]:
        print(f"  {args.output_dir / f'reranker_{name}.jsonl'}")


if __name__ == "__main__":
    main()
