/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe */
    get: operations['health_check_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/models': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The BYOK selection menu (tested game models only)
     * @description Tested game models, display labels, and their same-credential rescue models.
     *     First entry = the default for a bare key.
     */
    get: operations['supported_models_models_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Instant start: solo human (role choice) or LLM-only */
    post: operations['create_game_games_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/rooms': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Browse waiting rooms (public)
     * @description Waiting rooms only, newest first. Rooms older than ROOM_LIST_TTL_SECONDS are
     *     hidden, not expired — durability revives abandoned rooms across restarts, so an
     *     unfiltered list would fill with the undead; the direct room URL keeps working.
     */
    get: operations['list_rooms_rooms_get'];
    put?: never;
    /**
     * Create a multiplayer waiting room (humans join via /join)
     * @description The multiplayer door: no human/role fields exist in its contract — a room
     *     seats humans only through POST /join and always deals random roles. All
     *     per-id routes stay under /games/{id}: the /start swap keeps the id, so the
     *     room URL is the game URL for its whole life.
     */
    post: operations['create_room_rooms_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/lock': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Lock or unlock a waiting room (host only)
     * @description The host's door policy: locked bounces /join (409) without touching seated
     *     players. Kicking a seated player is deliberately NOT offered (deferred ruling
     *     2026-08-20): pre-start, lock covers the griefing case; post-start, the AFK
     *     delegate already absorbs deserters.
     */
    post: operations['lock_room_games__game_id__lock_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/join': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Claim a human seat in a waiting room */
    post: operations['join_game_games__game_id__join_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/rejoin': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Restore a lost seat cookie from the token's body copy
     * @description Cookie-loss recovery (new device, cleared browsing data): the stashed body-copy
     *     token re-proves seat ownership and re-sets the cookie. Serves both registry phases
     *     — position_of lives on GameLobby and GameSession alike. A seat lost for good (both
     *     copies gone) is an AFK seat: the game must not stall on it (slice 4's timer).
     */
    post: operations['rejoin_game_games__game_id__rejoin_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start the waiting room's game (host only)
     * @description The registry swap: the GameLobby is replaced by a real GameSession under the
     *     same game_id (the room URL survives). Check-then-swap is atomic — no await
     *     between them, so a concurrent /start or /join cannot interleave.
     */
    post: operations['start_game_games__game_id__start_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Status snapshot */
    get: operations['game_status_games__game_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/turns': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit the human seat's action */
    post: operations['submit_turn_games__game_id__turns_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * SSE event stream
     * @description Endpoint for the SSE connection — the response never ends; _sse yields frames
     *     for the connection's lifetime.
     *     token -> the seat cookie: proves which seat the viewer owns (private tiers);
     *                     "" = spectator (public tier only), unknown token = 403.
     *     last_seq: int -> the client's own cursor: the last event id it already has; frozen at
     *                     connection time. First connection to game starts at 0.
     *     Last-Event-ID header -> the living cursor (ruled 2026-08-18): the browser's auto-
     *                     reconnect reuses the ORIGINAL url verbatim (query cursor = a fossil
     *                     from construction) and carries its real position in this header.
     *                     Header wins when present; only durable seqs ever land in it because
     *                     pacing frames carry no id line.
     */
    get: operations['event_stream_games__game_id__events_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/replays': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Browse finished games (newest first) */
    get: operations['list_replays_replays_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/replays/{game_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One finished game's full event log */
    get: operations['get_replay_replays__game_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AddressedTargetsAnnotation
     * @description Structured who-this-addresses tags. Joins the speech via about_channel_seq.
     */
    AddressedTargetsAnnotation: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'addressed_targets';
      /** About Channel Seq */
      about_channel_seq: number;
      /** Player */
      player: string;
      /** Targets */
      targets: components['schemas']['WireAddressedTarget'][];
    };
    /** BulletsRemaining */
    BulletsRemaining: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'bullets_remaining';
      /** Player */
      player: string;
      /** Count */
      count: number;
    };
    /**
     * DaySummary
     * @description Shown next morning — client render rule, no buffer (buffers gate entitlement;
     *     render timing gates pacing).
     */
    DaySummary: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'day_summary';
      /** Summary */
      summary: string;
    };
    /**
     * DaySummaryStructured
     * @description O-tier structured form of the summary (accusations / role claims / alliances).
     */
    DaySummaryStructured: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'day_summary_structured';
      /** Data */
      data: {
        [key: string]: unknown;
      };
    };
    /**
     * FiringReasonAnnotation
     * @description Scheduler trace for a turn: why it fired. Joins the speech/pass via about_channel_seq.
     */
    FiringReasonAnnotation: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'firing_reason';
      /** About Channel Seq */
      about_channel_seq: number;
      /** Player */
      player: string;
      /**
       * Tier
       * @enum {string}
       */
      tier: 'reactive' | 'proactive';
      /** Owes */
      owes?: string[];
    };
    /**
     * GameCreated
     * @description POST /games and POST /games/{id}/start response.
     */
    GameCreated: {
      /** Game Id */
      game_id: string;
      /** Seat Token */
      seat_token?: string | null;
    };
    /**
     * GameOver
     * @description Thin by ruling: an entitlement flip, not a data package — the server follows it with
     *     the withheld observer-tier backlog from the durable log.
     */
    GameOver: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'game_over';
      /**
       * Winner
       * @enum {string}
       */
      winner: 'villagers' | 'wolves' | 'serial_killer';
    };
    /** GameStarted */
    GameStarted: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'game_started';
      /** Seats */
      seats: string[];
      /** Cast Role Counts */
      cast_role_counts: {
        [key: string]: number;
      };
    };
    /**
     * GameStatus
     * @description GET /games/{id} response: the poll-side snapshot (the stream carries the rest).
     *
     *     One shape for both registry phases — a lobby fills only the header trio
     *     (game_id, state, players) and leaves the game fields at their defaults.
     */
    GameStatus: {
      /** Game Id */
      game_id: string;
      /** State */
      state: string;
      /** Players */
      players?: string[];
      /**
       * Max Seats
       * @default 0
       */
      max_seats: number;
      /**
       * Name
       * @default
       */
      name: string;
      /**
       * Locked
       * @default false
       */
      locked: boolean;
      /** Human Players */
      human_players?: string[];
      /** You */
      you?: string | null;
      /**
       * Pending Input
       * @default false
       */
      pending_input: boolean;
      /** Pending Seats */
      pending_seats?: string[];
      /** Deadlines */
      deadlines?: {
        [key: string]: string;
      };
      /**
       * Game Over
       * @default false
       */
      game_over: boolean;
      /**
       * Last Seq
       * @default 0
       */
      last_seq: number;
      /** Alive Role Counts */
      alive_role_counts?: {
        [key: string]: number;
      };
      /** Error */
      error?: string | null;
    };
    /**
     * GmMessage
     * @description Verbatim GM narration (record fidelity outranks derivability for authored text).
     */
    GmMessage: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'gm_message';
      /** Channel Seq */
      channel_seq: number;
      /** Text */
      text: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * InputRequest
     * @description The human seat's turn prompt (interrupt surface). Night instances fire inside a
     *     parallel superstep — resume semantics gated on the spike verification.
     */
    InputRequest: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'input_request';
      /** Player */
      player: string;
      /**
       * Action Kind
       * @enum {string}
       */
      action_kind:
        | 'discuss'
        | 'vote'
        | 'wolf_discuss'
        | 'wolf_vote'
        | 'healer_target'
        | 'investigator_target'
        | 'serial_killer_target'
        | 'vigilante_target';
      /** Candidates */
      candidates?: string[];
      /** Deadline */
      deadline?: string | null;
    };
    /**
     * InvestigationResult
     * @description Survival-gated in the engine node: no committed delta -> this event never exists.
     */
    InvestigationResult: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'investigation_result';
      /** Player */
      player: string;
      /** Target */
      target: string;
      /** Role */
      role: string;
    };
    /**
     * JoinGame
     * @description POST /games/{id}/join body. No role field on purpose: rooms deal random
     *     seats (role choice is solo-only, on the instant-start path).
     */
    JoinGame: {
      /**
       * Name
       * @default human
       */
      name: string;
    };
    /**
     * LynchResult
     * @description The day death atom (= the dead_roster delta) + the free-rider fields the node computed.
     */
    LynchResult: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'lynch_result';
      /**
       * Outcome
       * @enum {string}
       */
      outcome: 'lynched' | 'tie' | 'abstain' | 'no_vote';
      /** Player */
      player?: string | null;
      /** Role */
      role?: string | null;
      /** Vote Counts */
      vote_counts: {
        [key: string]: number;
      };
      /** No Lynch Streak */
      no_lynch_streak: number;
    };
    /**
     * ModelRow
     * @description One entry of the GET /models BYOK menu.
     */
    ModelRow: {
      /** Model */
      model: string;
      /** Label */
      label: string;
      /** Rescue Model */
      rescue_model: string | null;
    };
    /**
     * ModelsMenu
     * @description GET /models response. First entry = the default for a bare key.
     */
    ModelsMenu: {
      /** Models */
      models: components['schemas']['ModelRow'][];
    };
    /**
     * NewGame
     * @description POST /games body: the instant-start (solo / LLM-only) door. Multiplayer
     *     rooms are created at POST /rooms — a deliberately separate contract.
     */
    NewGame: {
      /**
       * Human
       * @default false
       */
      human: boolean;
      /** Human Role */
      human_role?: string | null;
      /**
       * Api Key
       * @default
       */
      api_key: string;
      /**
       * Model
       * @default
       */
      model: string;
    };
    /**
     * NewRoom
     * @description POST /rooms body: the multiplayer door. No human/role fields ON PURPOSE —
     *     a room seats humans only via POST /join and always deals random roles, so the
     *     concept is unrepresentable here instead of guarded; extra="forbid" turns a
     *     client sending instant-start fields into a clean 422.
     */
    NewRoom: {
      /**
       * Api Key
       * @default
       */
      api_key: string;
      /**
       * Model
       * @default
       */
      model: string;
      /**
       * Name
       * @default
       */
      name: string;
    };
    /**
     * NightAction
     * @description O-tier committed target of a single-target night actor. No seat ack by ruling —
     *     the seat re-learns its act from dawn's gm_message; the live client echoes locally.
     */
    NightAction: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'night_action';
      /** Actor */
      actor: string;
      /** Role */
      role: string;
      /** Target */
      target: string;
    };
    /** NightDeath */
    NightDeath: {
      /** Player */
      player: string;
      /** Role */
      role: string;
      /** Attacker Types */
      attacker_types: ('wolves' | 'serial_killer' | 'vigilante')[];
    };
    /**
     * NightResult
     * @description The night death atom (= the dead_roster delta) + free-riders. Empty deaths = quiet
     *     night. Silent whiffs (immune SK) appear NOWHERE here — absence is the design.
     */
    NightResult: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'night_result';
      /** Deaths */
      deaths: components['schemas']['NightDeath'][];
      save?: components['schemas']['NightSave'] | null;
    };
    /** NightSave */
    NightSave: {
      /** Player */
      player: string;
      /** Attacker Types */
      attacker_types: ('wolves' | 'serial_killer' | 'vigilante')[];
    };
    /** PackRosterUpdate */
    PackRosterUpdate: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'pack_roster_update';
      /** Surviving Wolves */
      surviving_wolves: string[];
    };
    /**
     * PassMarker
     * @description A discussion turn that produced no speech — hidden from the table, observer-only.
     */
    PassMarker: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'pass_marker';
      /** Channel Seq */
      channel_seq: number;
      /** Player */
      player: string;
      /** Pass Reason */
      pass_reason?: ('voluntary' | 'novelty_gated' | 'generation_failed') | null;
      /**
       * Gated
       * @default false
       */
      gated: boolean;
      /** Gated Candidate */
      gated_candidate?: string | null;
    };
    /**
     * PhaseChange
     * @description Node-identity marker: anchored on initialize_game/one_more_day (day), START_VOTING
     *     (voting), and NIGHT_START (night).
     */
    PhaseChange: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'phase_change';
      /**
       * Phase
       * @enum {string}
       */
      phase: 'day' | 'voting' | 'night';
    };
    /**
     * RejoinGame
     * @description POST /games/{id}/rejoin body: re-prove seat ownership after cookie loss
     *     (new device, cleared browsing data) with the stashed body-copy token.
     */
    RejoinGame: {
      /** Token */
      token: string;
    };
    /**
     * ReplayBase
     * @description The metadata half — one row of GET /replays, and the columns both models share.
     */
    ReplayBase: {
      /** Game Id */
      game_id: string;
      /** Finished At */
      finished_at?: string | null;
      /** Winner */
      winner: string;
      /** Days */
      days: number;
      /** N Events */
      n_events: number;
      /** N Humans */
      n_humans: number;
      /** Cast Role Counts */
      cast_role_counts: {
        [key: string]: number;
      };
    };
    /**
     * ReplayGame
     * @description GET /replays/{id}: the summary plus the full event log.
     *
     *     ``events`` is declared as the discriminated union (not ``list[dict]``, which the
     *     table keeps for its JSONB column) so the 27-member event schema lands in
     *     /openapi.json — the frontend's TS event types are generated from it (ruled
     *     2026-08-20). Side effect: stored rows re-validate on the way out, so archive
     *     drift fails loudly here instead of shipping mystery dicts.
     */
    ReplayGame: {
      /** Game Id */
      game_id: string;
      /** Finished At */
      finished_at?: string | null;
      /** Winner */
      winner: string;
      /** Days */
      days: number;
      /** N Events */
      n_events: number;
      /** N Humans */
      n_humans: number;
      /** Cast Role Counts */
      cast_role_counts: {
        [key: string]: number;
      };
      /** Events */
      events: (
        | components['schemas']['GameStarted']
        | components['schemas']['RoleAssigned']
        | components['schemas']['RolesAssigned']
        | components['schemas']['PhaseChange']
        | components['schemas']['GameOver']
        | components['schemas']['TurnStarted']
        | components['schemas']['Speech']
        | components['schemas']['PassMarker']
        | components['schemas']['FiringReasonAnnotation']
        | components['schemas']['AddressedTargetsAnnotation']
        | components['schemas']['StrategyUpdate']
        | components['schemas']['InputRequest']
        | components['schemas']['DaySummary']
        | components['schemas']['DaySummaryStructured']
        | components['schemas']['VoteCast']
        | components['schemas']['GmMessage']
        | components['schemas']['LynchResult']
        | components['schemas']['RosterUpdate']
        | components['schemas']['PackRosterUpdate']
        | components['schemas']['NightAction']
        | components['schemas']['WolfMessage']
        | components['schemas']['WolfVote']
        | components['schemas']['WolfKillDecided']
        | components['schemas']['NightResult']
        | components['schemas']['InvestigationResult']
        | components['schemas']['VigilanteConfirmation']
        | components['schemas']['BulletsRemaining']
      )[];
    };
    /**
     * RoleAssigned
     * @description Seat-private deal: one per seat at game start.
     */
    RoleAssigned: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'role_assigned';
      /** Player */
      player: string;
      /** Role */
      role: string;
      /** Pack */
      pack?: string[] | null;
      /** Bullets */
      bullets?: number | null;
    };
    /**
     * RolesAssigned
     * @description O-tier full deal at game start: nobody receives it live; exists so the game_over
     *     backlog replay has survivor roles from minute zero.
     */
    RolesAssigned: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'roles_assigned';
      /** Roles */
      roles: {
        [key: string]: string;
      };
    };
    /**
     * RoomCreated
     * @description POST /rooms response.
     */
    RoomCreated: {
      /** Game Id */
      game_id: string;
      /** Host Key */
      host_key: string;
    };
    /**
     * RoomSummary
     * @description One row of GET /rooms: the public face of a waiting room. Also the POST /lock
     *     response (the host's fresh view after flipping the flag). Never any secret —
     *     no host_key, no tokens.
     */
    RoomSummary: {
      /** Game Id */
      game_id: string;
      /** Name */
      name: string;
      /** Players */
      players: string[];
      /** Max Seats */
      max_seats: number;
      /** Locked */
      locked: boolean;
      /** Created At */
      created_at: string;
    };
    /**
     * RosterUpdate
     * @description Union only: the translator merges the wolf-partitioned survivor lists before the
     *     public tier ever sees them.
     */
    RosterUpdate: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'roster_update';
      /** Surviving Players */
      surviving_players: string[];
    };
    /**
     * SeatJoined
     * @description POST /games/{id}/join and POST /games/{id}/rejoin response.
     */
    SeatJoined: {
      /** Position */
      position: number;
      /** Token */
      token: string;
    };
    /** Speech */
    Speech: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'speech';
      /** Channel Seq */
      channel_seq: number;
      /** Player */
      player: string;
      /** Message */
      message: string;
    };
    /** StrategyUpdate */
    StrategyUpdate: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'strategy_update';
      /** Player */
      player: string;
      /** Strategy */
      strategy: string;
    };
    /**
     * TurnAccepted
     * @description POST /games/{id}/turns response.
     */
    TurnAccepted: {
      /**
       * Status
       * @default accepted
       */
      status: string;
    };
    /**
     * TurnStarted
     * @description Edge-emitted (route_speaker): who is about to speak. Not a promise of speech.
     */
    TurnStarted: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'turn_started';
      /** Player */
      player: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * VigilanteConfirmation
     * @description Private immune-whiff confirmation: the shot target is the serial killer.
     */
    VigilanteConfirmation: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'vigilante_confirmation';
      /** Player */
      player: string;
      /** Target */
      target: string;
    };
    /**
     * VoteCast
     * @description Ballot content, released as a batch at COLLECT_VOTES from the translator buffer.
     */
    VoteCast: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'vote_cast';
      /** Voter */
      voter: string;
      /** Votee */
      votee: string;
    };
    /** WireAddressedTarget */
    WireAddressedTarget: {
      /** Target */
      target: string;
      /**
       * Addressed Form
       * @enum {string}
       */
      addressed_form: 'question' | 'response' | 'mention';
      /**
       * Stance
       * @enum {string}
       */
      stance: 'accusation' | 'defense' | 'agreement' | 'neutral';
    };
    /**
     * WolfKillDecided
     * @description The pack's plurality tally (random tiebreak) — the only way a wolf seat learns it
     *     before dawn.
     */
    WolfKillDecided: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'wolf_kill_decided';
      /** Target */
      target: string;
    };
    /**
     * WolfMessage
     * @description Wolf-channel talk. wolf == "game_master" for the server-authored SK-whiff note.
     */
    WolfMessage: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'wolf_message';
      /** Round */
      round: number;
      /** Wolf */
      wolf: string;
      /** Message */
      message: string;
    };
    /**
     * WolfVote
     * @description Binding kill vote — buffered by the translator until the tally (blind voting +
     *     wire/state parity), then flushed together with wolf_kill_decided.
     */
    WolfVote: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'wolf_vote';
      /** Wolf */
      wolf: string;
      /** Votee */
      votee: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  supported_models_models_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ModelsMenu'];
        };
      };
    };
  };
  create_game_games_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewGame'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GameCreated'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_rooms_rooms_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoomSummary'][];
        };
      };
    };
  };
  create_room_rooms_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewRoom'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoomCreated'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  lock_room_games__game_id__lock_post: {
    parameters: {
      query?: {
        host_key?: string;
        locked?: boolean;
      };
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoomSummary'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  join_game_games__game_id__join_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['JoinGame'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SeatJoined'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  rejoin_game_games__game_id__rejoin_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RejoinGame'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SeatJoined'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  start_game_games__game_id__start_post: {
    parameters: {
      query?: {
        host_key?: string;
      };
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GameCreated'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  game_status_games__game_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GameStatus'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  submit_turn_games__game_id__turns_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TurnAccepted'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  event_stream_games__game_id__events_get: {
    parameters: {
      query?: {
        last_seq?: number;
      };
      header?: {
        'last-event-id'?: string | null;
      };
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_replays_replays_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReplayBase'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_replay_replays__game_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReplayGame'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
