/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe */
    get: operations['health_check_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/models': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The served-game model menu (tested models only), and what the house will pay for
     * @description Every tested model with its rescue, whether the house pays for it, and which one is
     *     the default right now; plus the house's purse for today, so the client can say
     *     "house pays, 3 left" or "your key needed" before the player submits.
     */
    get: operations['supported_models_models_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Instant start: solo human (role choice) or LLM-only */
    post: operations['create_game_games_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Status snapshot */
    get: operations['game_status_games__game_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/key': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Resume a key-funded game after a restart by supplying the key again
     * @description Any seat holder may fund the resume; spectators may not. The key is tried on the
     *     provider first (422 with its complaint), then the game continues from its checkpoint.
     *     409 when the game is not waiting for a key.
     */
    post: operations['fund_game_games__game_id__key_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/turns': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit the human seat's action */
    post: operations['submit_turn_games__game_id__turns_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * SSE event stream
     * @description Stream entitled durable events plus public ephemeral pacing frames.
     *
     *     ``last_seq`` is the cursor frozen into the original URL. On automatic browser
     *     reconnection, ``Last-Event-ID`` carries the live cursor and therefore wins when
     *     valid. Pacing frames have no ID, so they never advance that durable cursor.
     */
    get: operations['event_stream_games__game_id__events_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/rooms': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Browse waiting rooms (public)
     * @description Return non-stale waiting rooms newest first without expiring direct URLs.
     */
    get: operations['list_rooms_rooms_get'];
    put?: never;
    /**
     * Create a multiplayer waiting room (humans join via /join)
     * @description Create a lobby whose identifier remains stable when the game starts.
     *
     *     Humans enter only through ``/join`` and roles remain random. The model is resolved
     *     and the house consulted here so the host learns early; the cap is checked again at
     *     start, which is when the game actually costs anything.
     */
    post: operations['create_room_rooms_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/lock': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Lock or unlock a waiting room (host only) */
    post: operations['lock_room_games__game_id__lock_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/join': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Claim a human seat in a waiting room */
    post: operations['join_game_games__game_id__join_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/rejoin': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore a lost seat cookie from the token's body copy */
    post: operations['rejoin_game_games__game_id__rejoin_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/games/{game_id}/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start the waiting room's game (host only)
     * @description Replace the lobby with a running session under the same ID (registry.start).
     */
    post: operations['start_game_games__game_id__start_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/replays': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Browse finished games (newest first) */
    get: operations['list_replays_replays_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/replays/{game_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One finished game's full event log */
    get: operations['get_replay_replays__game_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/house': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The house's purse as of now */
    get: operations['read_house_admin_house_get'];
    /** Change the house's knobs, live */
    put: operations['update_house_admin_house_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AddressedTargetsAnnotation
     * @description Structured who-this-addresses tags. Joins the speech via about_channel_seq.
     */
    AddressedTargetsAnnotation: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'addressed_targets';
      /** About Channel Seq */
      about_channel_seq: number;
      /** Player */
      player: string;
      /** Targets */
      targets: components['schemas']['WireAddressedTarget'][];
    };
    /** BulletsRemaining */
    BulletsRemaining: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'bullets_remaining';
      /** Player */
      player: string;
      /** Count */
      count: number;
    };
    /**
     * DaySummary
     * @description Shown next morning — client render rule, no buffer (buffers gate entitlement;
     *     render timing gates pacing).
     */
    DaySummary: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'day_summary';
      /** Summary */
      summary: string;
    };
    /**
     * DaySummaryStructured
     * @description O-tier structured form of the summary (accusations / role claims / alliances).
     */
    DaySummaryStructured: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'day_summary_structured';
      /** Data */
      data: {
        [key: string]: unknown;
      };
    };
    /**
     * FiringReasonAnnotation
     * @description Scheduler trace for a turn: why it fired. Joins the speech/pass via about_channel_seq.
     */
    FiringReasonAnnotation: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'firing_reason';
      /** About Channel Seq */
      about_channel_seq: number;
      /** Player */
      player: string;
      /**
       * Tier
       * @enum {string}
       */
      tier: 'reactive' | 'proactive';
      /** Owes */
      owes?: string[];
    };
    /**
     * FundGame
     * @description POST /games/{id}/key body: a seat holder's key to resume a game that lost its
     *     funding in a restart. Tried on the provider before the game moves; never stored.
     */
    FundGame: {
      /** Api Key */
      api_key: string;
    };
    /**
     * GameCreated
     * @description POST /games and POST /games/{id}/start response.
     */
    GameCreated: {
      /** Game Id */
      game_id: string;
      /** Seat Token */
      seat_token?: string | null;
    };
    /**
     * GameOver
     * @description Thin by ruling: an entitlement flip, not a data package — the server follows it with
     *     the withheld observer-tier backlog from the durable log.
     */
    GameOver: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'game_over';
      /**
       * Winner
       * @enum {string}
       */
      winner: 'villagers' | 'wolves' | 'serial_killer';
    };
    /** GameStarted */
    GameStarted: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'game_started';
      /** Seats */
      seats: string[];
      /** Cast Role Counts */
      cast_role_counts: {
        [key: string]: number;
      };
    };
    /**
     * GameStatus
     * @description GET /games/{id} response: the poll-side snapshot (the stream carries the rest).
     *
     *     One shape for both registry phases — a lobby fills only the header trio
     *     (game_id, state, players) and leaves the game fields at their defaults.
     */
    GameStatus: {
      /** Game Id */
      game_id: string;
      /**
       * State
       * @enum {string}
       */
      state: 'waiting' | 'running' | 'finished' | 'dropped';
      /** Server Time */
      server_time: string;
      /** Players */
      players?: string[];
      /**
       * Max Seats
       * @default 0
       */
      max_seats: number;
      /**
       * Name
       * @default
       */
      name: string;
      /**
       * Locked
       * @default false
       */
      locked: boolean;
      /** Human Players */
      human_players?: string[];
      /** You */
      you?: string | null;
      /**
       * Pending Input
       * @default false
       */
      pending_input: boolean;
      /** Pending Seats */
      pending_seats?: string[];
      /** Deadlines */
      deadlines?: {
        [key: string]: string;
      };
      /**
       * Game Over
       * @default false
       */
      game_over: boolean;
      /**
       * Last Seq
       * @default 0
       */
      last_seq: number;
      /**
       * Awaiting Key
       * @default false
       */
      awaiting_key: boolean;
      /** Winner */
      winner?: ('villagers' | 'wolves' | 'serial_killer') | null;
      /**
       * Archived
       * @default false
       */
      archived: boolean;
      /** Alive Role Counts */
      alive_role_counts?: {
        [key: string]: number;
      };
      /** Error */
      error?: string | null;
    };
    /**
     * GmMessage
     * @description Verbatim GM narration (record fidelity outranks derivability for authored text).
     */
    GmMessage: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'gm_message';
      /** Channel Seq */
      channel_seq: number;
      /** Text */
      text: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * HouseFunding
     * @description The house's purse for today, as GET /models reports it to the client.
     */
    HouseFunding: {
      /** Enabled */
      enabled: boolean;
      /** Games Per Day */
      games_per_day: number;
      /** Remaining */
      remaining: number;
      /** Reset At */
      reset_at: string;
    };
    /**
     * HouseUpdate
     * @description PUT /admin/house body: any subset of the knobs.
     */
    HouseUpdate: {
      /** Enabled */
      enabled?: boolean | null;
      /** Default Model */
      default_model?: string | null;
      /** Games Per Day */
      games_per_day?: number | null;
    };
    /**
     * HouseView
     * @description GET/PUT /admin/house response: the purse plus the knobs behind it.
     */
    HouseView: {
      /** Enabled */
      enabled: boolean;
      /** Games Per Day */
      games_per_day: number;
      /** Remaining */
      remaining: number;
      /** Reset At */
      reset_at: string;
      /** Default Model */
      default_model: string;
      /** Used Today */
      used_today: number;
    };
    /**
     * InputRequest
     * @description The human seat's turn prompt (interrupt surface). Night instances fire inside a
     *     parallel superstep — resume semantics gated on the spike verification.
     */
    InputRequest: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'input_request';
      /** Player */
      player: string;
      /**
       * Action Kind
       * @enum {string}
       */
      action_kind:
        | 'discuss'
        | 'vote'
        | 'wolf_discuss'
        | 'wolf_vote'
        | 'healer_target'
        | 'investigator_target'
        | 'serial_killer_target'
        | 'vigilante_target';
      /** Candidates */
      candidates?: string[];
      /** Deadline */
      deadline?: string | null;
    };
    /**
     * InvestigationResult
     * @description Survival-gated in the engine node: no committed delta -> this event never exists.
     */
    InvestigationResult: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'investigation_result';
      /** Player */
      player: string;
      /** Target */
      target: string;
      /**
       * Role
       * @enum {string}
       */
      role: 'villager' | 'wolf' | 'investigator' | 'healer' | 'serial_killer' | 'vigilante';
    };
    /**
     * JoinGame
     * @description POST /games/{id}/join body. No role field on purpose: rooms deal random
     *     seats (role choice is solo-only, on the instant-start path).
     */
    JoinGame: {
      /**
       * Name
       * @default human
       */
      name: string;
    };
    /**
     * LynchResult
     * @description The day death atom (= the dead_roster delta) + the free-rider fields the node computed.
     */
    LynchResult: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'lynch_result';
      /**
       * Outcome
       * @enum {string}
       */
      outcome: 'lynched' | 'tie' | 'abstain' | 'no_vote';
      /** Player */
      player?: string | null;
      /** Role */
      role?:
        | ('villager' | 'wolf' | 'investigator' | 'healer' | 'serial_killer' | 'vigilante')
        | null;
      /** Vote Counts */
      vote_counts: {
        [key: string]: number;
      };
      /** No Lynch Streak */
      no_lynch_streak: number;
    };
    /**
     * ModelRow
     * @description One entry of the GET /models served-game menu.
     */
    ModelRow: {
      /** Model */
      model: string;
      /** Label */
      label: string;
      /** Rescue Model */
      rescue_model: string | null;
      /**
       * House Funded
       * @default false
       */
      house_funded: boolean;
      /**
       * Is Default
       * @default false
       */
      is_default: boolean;
      /**
       * Needs Key
       * @default true
       */
      needs_key: boolean;
    };
    /**
     * ModelsMenu
     * @description GET /models response: the menu, and what the house will pay for right now.
     */
    ModelsMenu: {
      /** Models */
      models: components['schemas']['ModelRow'][];
      house: components['schemas']['HouseFunding'];
    };
    /**
     * NewGame
     * @description POST /games body: the instant-start (solo / LLM-only) door. Multiplayer
     *     rooms are created at POST /rooms — a deliberately separate contract.
     */
    NewGame: {
      /**
       * Human
       * @default false
       */
      human: boolean;
      /** Human Role */
      human_role?:
        | ('villager' | 'wolf' | 'investigator' | 'healer' | 'serial_killer' | 'vigilante')
        | null;
      /**
       * Api Key
       * @default
       */
      api_key: string;
      /**
       * Model
       * @default
       */
      model: string;
    };
    /**
     * NewRoom
     * @description POST /rooms body: the multiplayer door. No human/role fields ON PURPOSE —
     *     a room seats humans only via POST /join and always deals random roles, so the
     *     concept is unrepresentable here instead of guarded; extra="forbid" turns a
     *     client sending instant-start fields into a clean 422.
     */
    NewRoom: {
      /**
       * Api Key
       * @default
       */
      api_key: string;
      /**
       * Model
       * @default
       */
      model: string;
      /**
       * Name
       * @default
       */
      name: string;
    };
    /**
     * NightAction
     * @description O-tier committed target of a single-target night actor. No seat ack by ruling —
     *     the seat re-learns its act from dawn's gm_message; the live client echoes locally.
     */
    NightAction: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'night_action';
      /** Actor */
      actor: string;
      /**
       * Role
       * @enum {string}
       */
      role: 'villager' | 'wolf' | 'investigator' | 'healer' | 'serial_killer' | 'vigilante';
      /** Target */
      target: string;
    };
    /** NightDeath */
    NightDeath: {
      /** Player */
      player: string;
      /**
       * Role
       * @enum {string}
       */
      role: 'villager' | 'wolf' | 'investigator' | 'healer' | 'serial_killer' | 'vigilante';
      /** Attacker Types */
      attacker_types: ('wolves' | 'serial_killer' | 'vigilante')[];
    };
    /**
     * NightResult
     * @description The night death atom (= the dead_roster delta) + free-riders. Empty deaths = quiet
     *     night. Silent whiffs (immune SK) appear NOWHERE here — absence is the design.
     */
    NightResult: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'night_result';
      /** Deaths */
      deaths: components['schemas']['NightDeath'][];
      save?: components['schemas']['NightSave'] | null;
    };
    /** NightSave */
    NightSave: {
      /** Player */
      player: string;
      /** Attacker Types */
      attacker_types: ('wolves' | 'serial_killer' | 'vigilante')[];
    };
    /** PackRosterUpdate */
    PackRosterUpdate: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'pack_roster_update';
      /** Surviving Wolves */
      surviving_wolves: string[];
    };
    /**
     * PassMarker
     * @description A discussion turn that produced no speech — hidden from the table, observer-only.
     */
    PassMarker: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'pass_marker';
      /** Channel Seq */
      channel_seq: number;
      /** Player */
      player: string;
      /** Pass Reason */
      pass_reason?: ('voluntary' | 'novelty_gated' | 'generation_failed') | null;
      /**
       * Gated
       * @default false
       */
      gated: boolean;
      /** Gated Candidate */
      gated_candidate?: string | null;
    };
    /**
     * PhaseChange
     * @description Node-identity marker: anchored on initialize_game/one_more_day (day), START_VOTING
     *     (voting), and NIGHT_START (night).
     */
    PhaseChange: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'phase_change';
      /**
       * Phase
       * @enum {string}
       */
      phase: 'day' | 'voting' | 'night';
    };
    /**
     * RejoinGame
     * @description POST /games/{id}/rejoin body: re-prove seat ownership after cookie loss
     *     (new device, cleared browsing data) with the stashed body-copy token.
     */
    RejoinGame: {
      /** Token */
      token: string;
    };
    /**
     * ReplayBase
     * @description One row returned by ``GET /replays``.
     */
    ReplayBase: {
      /** Game Id */
      game_id: string;
      /** Finished At */
      finished_at?: string | null;
      /**
       * Winner
       * @enum {string}
       */
      winner: 'villagers' | 'wolves' | 'serial_killer';
      /** Days */
      days: number;
      /** N Events */
      n_events: number;
      /** N Humans */
      n_humans: number;
      /** Cast Role Counts */
      cast_role_counts: {
        [key: string]: number;
      };
      /**
       * Model
       * @default
       */
      model: string;
    };
    /**
     * ReplayGame
     * @description One complete replay with every stored event revalidated for the wire.
     */
    ReplayGame: {
      /** Game Id */
      game_id: string;
      /** Finished At */
      finished_at?: string | null;
      /**
       * Winner
       * @enum {string}
       */
      winner: 'villagers' | 'wolves' | 'serial_killer';
      /** Days */
      days: number;
      /** N Events */
      n_events: number;
      /** N Humans */
      n_humans: number;
      /** Cast Role Counts */
      cast_role_counts: {
        [key: string]: number;
      };
      /**
       * Model
       * @default
       */
      model: string;
      /** Events */
      events: (
        | components['schemas']['GameStarted']
        | components['schemas']['RoleAssigned']
        | components['schemas']['RolesAssigned']
        | components['schemas']['PhaseChange']
        | components['schemas']['GameOver']
        | components['schemas']['TurnStarted']
        | components['schemas']['Speech']
        | components['schemas']['PassMarker']
        | components['schemas']['FiringReasonAnnotation']
        | components['schemas']['AddressedTargetsAnnotation']
        | components['schemas']['StrategyUpdate']
        | components['schemas']['InputRequest']
        | components['schemas']['DaySummary']
        | components['schemas']['DaySummaryStructured']
        | components['schemas']['VoteCast']
        | components['schemas']['GmMessage']
        | components['schemas']['LynchResult']
        | components['schemas']['RosterUpdate']
        | components['schemas']['PackRosterUpdate']
        | components['schemas']['NightAction']
        | components['schemas']['WolfMessage']
        | components['schemas']['WolfVote']
        | components['schemas']['WolfKillDecided']
        | components['schemas']['NightResult']
        | components['schemas']['InvestigationResult']
        | components['schemas']['VigilanteConfirmation']
        | components['schemas']['BulletsRemaining']
      )[];
    };
    /**
     * RoleAssigned
     * @description Seat-private deal: one per seat at game start.
     */
    RoleAssigned: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'role_assigned';
      /** Player */
      player: string;
      /**
       * Role
       * @enum {string}
       */
      role: 'villager' | 'wolf' | 'investigator' | 'healer' | 'serial_killer' | 'vigilante';
      /** Pack */
      pack?: string[] | null;
      /** Bullets */
      bullets?: number | null;
    };
    /**
     * RolesAssigned
     * @description O-tier full deal at game start: nobody receives it live; exists so the game_over
     *     backlog replay has survivor roles from minute zero.
     */
    RolesAssigned: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'roles_assigned';
      /** Roles */
      roles: {
        [key: string]: string;
      };
    };
    /**
     * RoomCreated
     * @description POST /rooms response.
     */
    RoomCreated: {
      /** Game Id */
      game_id: string;
      /** Host Key */
      host_key: string;
    };
    /**
     * RoomSummary
     * @description One row of GET /rooms: the public face of a waiting room. Also the POST /lock
     *     response (the host's fresh view after flipping the flag). Never any secret —
     *     no host_key, no tokens.
     */
    RoomSummary: {
      /** Game Id */
      game_id: string;
      /** Name */
      name: string;
      /** Players */
      players: string[];
      /** Max Seats */
      max_seats: number;
      /** Locked */
      locked: boolean;
      /** Created At */
      created_at: string;
    };
    /**
     * RosterUpdate
     * @description Union only: the translator merges the wolf-partitioned survivor lists before the
     *     public tier ever sees them.
     */
    RosterUpdate: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'roster_update';
      /** Surviving Players */
      surviving_players: string[];
    };
    /**
     * SeatJoined
     * @description POST /games/{id}/join and POST /games/{id}/rejoin response.
     */
    SeatJoined: {
      /** Token */
      token: string;
    };
    /** Speech */
    Speech: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'speech';
      /** Channel Seq */
      channel_seq: number;
      /** Player */
      player: string;
      /** Message */
      message: string;
    };
    /** StrategyUpdate */
    StrategyUpdate: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'strategy_update';
      /** Player */
      player: string;
      /** Strategy */
      strategy: string;
    };
    /**
     * TurnAccepted
     * @description POST /games/{id}/turns response.
     */
    TurnAccepted: {
      /**
       * Status
       * @default accepted
       */
      status: string;
    };
    /**
     * TurnStarted
     * @description Edge-emitted (route_speaker): who is about to speak. Not a promise of speech.
     */
    TurnStarted: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'turn_started';
      /** Player */
      player: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * VigilanteConfirmation
     * @description Private immune-whiff confirmation: the shot target is the serial killer.
     */
    VigilanteConfirmation: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'vigilante_confirmation';
      /** Player */
      player: string;
      /** Target */
      target: string;
    };
    /**
     * VoteCast
     * @description Ballot content, released as a batch at COLLECT_VOTES from the translator buffer.
     */
    VoteCast: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'vote_cast';
      /** Voter */
      voter: string;
      /** Votee */
      votee: string;
    };
    /** WireAddressedTarget */
    WireAddressedTarget: {
      /** Target */
      target: string;
      /**
       * Addressed Form
       * @enum {string}
       */
      addressed_form: 'question' | 'response' | 'mention';
      /**
       * Stance
       * @enum {string}
       */
      stance: 'accusation' | 'defense' | 'agreement' | 'neutral';
    };
    /**
     * WolfKillDecided
     * @description The pack's plurality tally (random tiebreak) — the only way a wolf seat learns it
     *     before dawn.
     */
    WolfKillDecided: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'wolf_kill_decided';
      /** Target */
      target: string;
    };
    /**
     * WolfMessage
     * @description Wolf-channel talk. wolf == "game_master" for the server-authored SK-whiff note.
     */
    WolfMessage: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'wolf_message';
      /** Round */
      round: number;
      /** Wolf */
      wolf: string;
      /** Message */
      message: string;
    };
    /**
     * WolfVote
     * @description Binding kill vote — buffered by the translator until the tally (blind voting +
     *     wire/state parity), then flushed together with wolf_kill_decided.
     */
    WolfVote: {
      /** Seq */
      seq: number;
      /** Day */
      day: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'wolf_vote';
      /** Wolf */
      wolf: string;
      /** Votee */
      votee: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  supported_models_models_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ModelsMenu'];
        };
      };
    };
  };
  create_game_games_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewGame'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GameCreated'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  game_status_games__game_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GameStatus'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  fund_game_games__game_id__key_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FundGame'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GameStatus'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  submit_turn_games__game_id__turns_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TurnAccepted'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  event_stream_games__game_id__events_get: {
    parameters: {
      query?: {
        last_seq?: number;
      };
      header?: {
        'last-event-id'?: string | null;
      };
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_rooms_rooms_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoomSummary'][];
        };
      };
    };
  };
  create_room_rooms_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewRoom'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoomCreated'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  lock_room_games__game_id__lock_post: {
    parameters: {
      query?: {
        host_key?: string;
        locked?: boolean;
      };
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoomSummary'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  join_game_games__game_id__join_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['JoinGame'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SeatJoined'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  rejoin_game_games__game_id__rejoin_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RejoinGame'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SeatJoined'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  start_game_games__game_id__start_post: {
    parameters: {
      query?: {
        host_key?: string;
      };
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GameCreated'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_replays_replays_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReplayBase'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_replay_replays__game_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReplayGame'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  read_house_admin_house_get: {
    parameters: {
      query?: never;
      header?: {
        'x-admin-token'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HouseView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_house_admin_house_put: {
    parameters: {
      query?: never;
      header?: {
        'x-admin-token'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['HouseUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HouseView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
